// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmLI2D0PKVMmS7eXZY71SiIPgO-AcLC8',
    appId: '1:1035993443430:web:99e7b884cc4954f09451a7',
    messagingSenderId: '1035993443430',
    projectId: 'accessories-ecommerce',
    authDomain: 'accessories-ecommerce.firebaseapp.com',
    storageBucket: 'accessories-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJuKY5SinKdDMwNcCxuOTVy0SXpcnkY8',
    appId: '1:1035993443430:android:667dfaf07288ed869451a7',
    messagingSenderId: '1035993443430',
    projectId: 'accessories-ecommerce',
    storageBucket: 'accessories-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLXrMmojlS4wKmMesUsNsn3pHuMr9P4Lo',
    appId: '1:1035993443430:ios:5a46c3a9fdbfb0c99451a7',
    messagingSenderId: '1035993443430',
    projectId: 'accessories-ecommerce',
    storageBucket: 'accessories-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.pamProyek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLXrMmojlS4wKmMesUsNsn3pHuMr9P4Lo',
    appId: '1:1035993443430:ios:5a46c3a9fdbfb0c99451a7',
    messagingSenderId: '1035993443430',
    projectId: 'accessories-ecommerce',
    storageBucket: 'accessories-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.pamProyek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYmLI2D0PKVMmS7eXZY71SiIPgO-AcLC8',
    appId: '1:1035993443430:web:8a6f430fad268e5c9451a7',
    messagingSenderId: '1035993443430',
    projectId: 'accessories-ecommerce',
    authDomain: 'accessories-ecommerce.firebaseapp.com',
    storageBucket: 'accessories-ecommerce.firebasestorage.app',
  );
}
